### ISSUE TITLE
Installer should prefer `pyproject.toml` over `requirements.txt`

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-python#125]
It seems that most Python projects have migrated to using `pyproject.toml`. If a `pyproject.toml` file exists, our installer should probably write the dependencies to that file, instead of to `requirements.txt`.

(In the absence of either of the files, creating a `requirements.txt` is fine, as creating a `pyproject.toml` is a whole thing)

**Comment by Mr0grog** [comment]
As a related issue, the installer currently fails with an error if you do not have a `requirements.txt` present.

For example, I have a project with `pyproject.toml` and the following happens:

```
$ # uv run python -m appsignal install
👋 Welcome to the AppSignal for Python installer!

Reach us at support@appsignal.com for support
Documentation available at https://docs.appsignal.com/python

Please enter the name of your application: ***
Please enter your Push API key: ***
Validating API key...

✅ API key is valid!

Writing the __appsignal__.py configuration file...


Traceback (most recent call last):
  File "<frozen runpy>", line 203, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/appenv/lib/python3.13/site-packages/appsignal/__main__.py", line 4, in <module>
    run()
    ~~~^^
  File "/appenv/lib/python3.13/site-packages/appsignal/cli/base.py", line 25, in run
    sys.exit(main(sys.argv[1:]))
             ~~~~^^^^^^^^^^^^^^
  File "/appenv/lib/python3.13/site-packages/appsignal/cli/base.py", line 39, in main
    return cmd.run()
           ~~~~~~~^^
  File "/appenv/lib/python3.13/site-packages/appsignal/cli/install.py", line 65, in run
    if self._search_dependency("django"):
       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/appenv/lib/python3.13/site-packages/appsignal/cli/install.py", line 113, in _search_dependency
    with open(requirement_file) as f:
         ~~~~^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

There’s no other output, so I assume this error was fatal, and don’t know if there are other setup steps that got skipped.
